name: CI

on: [push, pull_request]
  branches:
  - master    

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      run: Install-Module Pester -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run Tests
      run: Invoke-Pester -EnableExit
      shell: pwsh
