name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Pwsh
      uses: docker://mcr.microsoft.com/powershell:7.0.0-preview.3-ubuntu-xenial
      run: |
        pwsh -c "Install-Module Pester -Force -SkipPublisherCheck"
