name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Pester
      run: Install-Module Pester -Force -SkipPublisherCheck
      shell: pwsh
    - name: Run Tests
      run: Invoke-Pester
      shell: pwsh
